name: Java CI (Gradle)
on: [ push, pull_request ]
permissions:
  checks: write

jobs:
  build-java-17:
    uses: Siroshun09/gh-actions-workflows/.github/workflows/gradle.yml@v1
    with:
      java-version: '17'
      upload-artifacts: false
      upload-test-results: true
  build-java-21:
    uses: Siroshun09/gh-actions-workflows/.github/workflows/gradle.yml@v1
    with:
      java-version: '21'
      upload-artifacts: false
      upload-test-results: true
